# $FreeBSD$

SUBDIR=athp_QCA988X_hw2.0_board
SUBDIR+= athp_QCA988X_hw2.0_firmware-2
SUBDIR+= athp_QCA988X_hw2.0_firmware-4
SUBDIR+= athp_QCA988X_hw2.0_firmware-5

SUBDIR+= athp_QCA99X0_hw2.0_board
SUBDIR+= athp_QCA99X0_hw2.0_firmware-5

.include <bsd.subdir.mk>
