/*
 * Copyright (c) 2025, Adrian Chadd <adrian@FreeBSD.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#ifndef	__MTWN_MT7610_EEPROM_REG_H__
#define	__MTWN_MT7610_EEPROM_REG_H__

#define	MT7610_EEPROM_SIZE		512

/*
 * This is the layout of the MT7610 EEPROM / EFUSE.
 */

#define	MT7610_EEPROM_CHIP_ID			0x000
#define	MT7610_EEPROM_VERSION			0x002
#define	MT7610_EEPROM_MAC_ADDR			0x004

#define	MT7610_EEPROM_USAGE_MAP_START		0x1e0
#define	MT7610_EEPROM_USAGE_MAP_END		0x1fc

#define	MT7610_EEPROM_USAGE_MAP_SIZE		\
	(MT7610_EEPROM_USAGE_MAP_END - MT7610_EEPROM_USAGE_MAP_START + 1)

#endif	/* __MTWN_MT7610_EEPROM_REG_H__ */
