/*
 * Copyright (c) 2025, Adrian Chadd <adrian@FreeBSD.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#ifndef	__MTWN_MT7610_DMA_REG_H__
#define	__MTWN_MT7610_DMA_REG_H__

/* MCU request message header */
#define	MT7610_MCU_MSG_LEN			0x0000ffff
#define	MT7610_MCU_MSG_LEN_S			0
#define	MT7610_MCU_MSG_CMD_SEQ			0x000f0000
#define	MT7610_MCU_MSG_CMD_SEQ_S		16
#define	MT7610_MCU_MSG_CMD_TYPE			0x07f00000
#define	MT7610_MCU_MSG_CMD_TYPE_S		20
#define	MT7610_MCU_MSG_PORT			0x38000000
#define	MT7610_MCU_MSG_PORT_S			27
#define		MT7610_MCU_MSG_PORT_WLAN		0
#define		MT7610_MCU_MSG_PORT_CPU_RX_PORT		1
#define		MT7610_MCU_MSG_PORT_CPU_TX_PORT		2
#define		MT7610_MCU_MSG_PORT_HOST_PORT		3
#define		MT7610_MCU_MSG_PORT_VIRTUAL_CPU_RX_PORT	4
#define		MT7610_MCU_MSG_PORT_VIRTUAL_CPU_TX_PORT	5
#define		MT7610_MCU_MSG_PORT_DISCARD		6
#define	MT7610_MCU_MSG_TYPE			0xc0000000
#define	MT7610_MCU_MSG_TYPE_S			30
#define		MT7610_MCU_MSG_TYPE_CMD_ID		0x1

#endif	/* __MTWN_MT7610_REG_H__ */
